### ISSUE TITLE
Unknown status: Not Ready

### ISSUE THREAD

**Issue by Fabio72** [bertbert72/HomeAssistant_Powerlink#1]
I have a powermax pro with a powerlink2
I'm getting the Unknown status: Not Ready because I have a battery failure
How can I add a new payload?

Moreover i'm getting
WARNING (MainThread) [homeassistant.components.binary_sensor.mqtt] No matching payload found for entity: Closet with state_topic: home/alarm/sensor16
Becaouse the sensor 16 status is switching between Open/Low Batteries

**Comment by bertbert72** [comment]
Give that a go and see if it resolves your first issue at least.  For your second issue, that's possibly a limitation of the MQTT alarm implementation.  If you want me to try to map it to something I'll probably need you to enable debug logging and send me the log file.  In the ha_powerlink.py file change lines 15 & 16 to 

use_logfile = True
debug_level = 2

**Comment by Fabio72** [comment]
2018-06-07 13:21:30,661 DEBUG    Refresh HomeAssistant: pending
2018-06-07 13:21:32,262 DEBUG    Sensor 2 = Open, alarm = no
2018-06-07 13:21:32,263 DEBUG    Sensor 3 = Open, alarm = no
2018-06-07 13:21:32,265 DEBUG    Sensor 5 = Open, alarm = no
2018-06-07 13:21:32,267 DEBUG    Sensor 6 = Open, alarm = no
2018-06-07 13:21:32,269 DEBUG    Sensor 9 = Open, alarm = no
2018-06-07 13:21:32,273 DEBUG    Sensor 11 = Open, alarm = no
2018-06-07 13:21:32,277 DEBUG    Sensor 16 = Low Battery, alarm = no
2018-06-07 13:21:33,650 DEBUG    Sensor 2 = Open, alarm = no
2018-06-07 13:21:33,652 DEBUG    Sensor 3 = Open, alarm = no
2018-06-07 13:21:33,656 DEBUG    Sensor 5 = Open, alarm = no
2018-06-07 13:21:33,657 DEBUG    Sensor 6 = Open, alarm = no
2018-06-07 13:21:33,660 DEBUG    Sensor 9 = Open, alarm = no
2018-06-07 13:21:33,663 DEBUG    Sensor 11 = Open, alarm = no
2018-06-07 13:21:33,668 DEBUG    Sensor 16 = Low Battery, alarm = no
2018-06-07 13:21:35,048 DEBUG    Sensor 2 = Open, alarm = no
2018-06-07 13:21:35,049 DEBUG    Sensor 3 = Open, alarm = no
2018-06-07 13:21:35,052 DEBUG    Sensor 5 = Open, alarm = no
2018-06-07 13:21:35,053 DEBUG    Sensor 6 = Open, alarm = no
2018-06-07 13:21:35,056 DEBUG    Sensor 9 = Open, alarm = no
2018-06-07 13:21:35,058 DEBUG    Sensor 11 = Open, alarm = no
2018-06-07 13:21:35,062 DEBUG    Sensor 16 = Low Battery, alarm = no

**Comment by Fabio72** [comment]
I added
 `elif curr_status == "Not Ready":
new_status = 'disarmed'`
to get rid of the first problem

**Comment by bertbert72** [comment]
Did the change in the code not fix the first problem?  Did you have to all the elif as well?

Line 163:
if curr_status == "Ready" or curr_status == "Not Ready":

I've also put an update on to map the low battery sensor.  Not awesome but I'm assuming the sensor with the low battery has an open state.  You might want to test what happens if the sensor activates, i.e. does it still alarm?

**Comment by bertbert72** [comment]
I should also point out that I'm not at home at the moment, so can't test the changes...

**Comment by Fabio72** [comment]
The "not ready" issue has gone now. I added the elif to the old version of your script, now is not necessary any more.

Now I'm still getting
`2018-06-08 09:30:08 WARNING (MainThread) [homeassistant.components.binary_sensor.mqtt] No matching payload found for entity: Closet with state_topic: home/alarm/sensor16`
on Home assistant.

The sensor is configured as follow
`  - platform: mqtt
    state_topic: "home/alarm/sensor15"
    payload_on: Open
    payload_off: Ok
    device_class: motion
    name: Garage
  - platform: mqtt
    state_topic: "home/alarm/sensor16"
    payload_on: Open
    payload_off: Ok
    device_class: opening
    name: Closet`

The debug log
`<detector>
<zone>14</zone>
<loc>Custom2</loc>
<type>Perimeter</type>
<status />
<isalarm>no</isalarm>
</detector>
<detector>
<zone>15</zone>
<loc>Garage</loc>
<type>Delay 2</type>
<status />
<isalarm>no</isalarm>
</detector>
<detector>
<zone>16</zone>
<loc>Closet</loc>
<type>Interior</type>
<status>Low Battery</status>
<isalarm>no</isalarm>
</detector>
<detector>`

I still have to check the condition with panel armed and low battery sensor, but I'm remote as well and my home is not empty.

**Comment by Fabio72** [comment]
When the alarm is armed, the sensor is still in low battery mode on powerlink, but green
`<detector>
<zone>16</zone>
<loc>Closet</loc>
<type>Interior</type>
<status>Low Battery</status>
<isalarm>no</isalarm>`

Now, after restarting all the services, the error on HA as gone.

**Comment by bertbert72** [comment]
Ok, that's good.  One thing though - when the battery was low did you see sensor 16 flicking between "Open" and "Low Battery"?  Looking at the log file it seems it just stayed as "Low Battery".  If it was actually flicking between the states, I could get it to ignore "Low Battery", meaning I don't have to hardcode "Open".  If not, I'll leave it as is.

At some point I'd love to make this a native component rather than relying on MQTT.  It's hard to justify the time though given that this works ok and very few people seem to have the Powerlink 2, but it would allow a bit more flexibility for things like low battery states.  Some day maybe...

**Comment by Fabio72** [comment]
I changed
`elif status == STATE_LOWBAT:
status = STATE_OK`
Now when the alarm is disarmed, the sensor is closed.
When the alarm is armed, the sensor is flapping between open and closed.

By the way, thank you so much for writing this.

**Comment by bertbert72** [comment]
I don't have an easy way of replicating this beyond trying to find a battery that is low in charge.  It'll happen eventually.  However from what you say, I guess that the status is flicking between low battery and its actual state.  Hopefully...  In that case, this might be a better solution:

        elif status == STATE_LOWBAT:
            break

Basically ignore the sensor when it is reporting low battery and hope that next time it is checked it returns the real value.

**Comment by bertbert72** [comment]
Actually that's not quite right.  It should be:

    elif status == STATE_LOWBAT:
        continue

Otherwise it'll ignore the rest of the sensors

**Comment by Fabio72** [comment]
I will try, but now I had to change the battery because the sensor died...
It would be nice to have the payload low_battery on mqtt and home assistant, but I don't know where to start since I just started digging in it and I'm a bit overloaded
